# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
version: 2
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - binary: localizely-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - format_overrides:
      - goos: windows
        format: zip
    name_template: "localizely_cli_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "localizely/localizely-cli:latest"
      - "localizely/localizely-cli:{{ .Tag }}"
    dockerfile: Dockerfile.goreleaser
release:
  github:
    owner: localizely
    name: localizely-cli
